# Generated by Django 4.1.2 on 2022-10-13 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_account_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
    ]
