# Generated by Django 4.1.2 on 2022-10-17 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='user_id',
            new_name='user',
        ),
    ]
