# Generated by Django 4.1.2 on 2022-10-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_account_is_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='user',
            new_name='account',
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='document',
            name='img',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
