# Generated by Django 4.1.2 on 2022-10-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_document_file_alter_document_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(default='Docs/None/No-doc.pdf', upload_to='Docs/'),
        ),
    ]
