# Generated by Django 4.1.2 on 2022-10-17 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_account_file_account_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='file',
        ),
        migrations.RemoveField(
            model_name='account',
            name='img',
        ),
    ]
