# Generated by Django 4.1.2 on 2022-10-18 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_account_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_staff',
        ),
    ]
