# Generated by Django 4.1.2 on 2022-10-18 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_account_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_admin',
        ),
    ]
