# Generated by Django 4.1.2 on 2022-10-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_blogtitle_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='author',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
