# Generated by Django 4.1.2 on 2022-10-18 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_events_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
