# Generated by Django 4.1.2 on 2022-10-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_events_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('A', 'Approved'), ('R', 'Rejected'), ('U', 'Under Review')], default='U', max_length=1),
        ),
        migrations.AddField(
            model_name='title',
            name='country_of_origin',
            field=models.CharField(default='India', max_length=255),
        ),
        migrations.AddField(
            model_name='title',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='year',
            field=models.IntegerField(),
        ),
    ]
