# Generated by Django 4.1.2 on 2022-10-19 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_event_created_at_event_status_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='event',
            table='Event',
        ),
        migrations.AlterModelTable(
            name='title',
            table='Title',
        ),
    ]
