# Generated by Django 4.1.2 on 2022-10-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
