# Generated by Django 4.1.2 on 2022-10-20 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.ForeignKey(db_column='title_id', on_delete=django.db.models.deletion.CASCADE, to='blog.title'),
        ),
        migrations.RenameField(
            model_name='event',
            old_name='title',
            new_name='title_id',
        ),
    ]
