# Generated by Django 4.1.2 on 2022-10-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_reviewcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewcomment',
            name='reviewer_status',
            field=models.CharField(choices=[('A', 'Approved'), ('R', 'Rejected'), ('U', 'Under Review')], default='U', max_length=1),
        ),
    ]
