# Generated by Django 4.1.2 on 2022-10-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_reviewcomment_reviewer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='is_admin',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='role',
            name='is_author',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='role',
            name='is_content_writer',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='role',
            name='is_reviewer',
            field=models.BooleanField(default=1),
        ),
    ]
