# Generated by Django 4.1.2 on 2022-10-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_role_is_admin_alter_role_is_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='is_admin',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='role',
            name='is_author',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='role',
            name='is_content_writer',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='role',
            name='is_reviewer',
            field=models.BooleanField(default=0),
        ),
    ]
