# Generated by Django 4.1.2 on 2022-10-29 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_remove_reviewcomment_added_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title_id',
            field=models.ForeignKey(db_column='title_id', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='blog.title'),
        ),
    ]
