# Generated by Django 4.1.2 on 2022-10-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_remove_event_user_alter_event_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='author',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
