# Generated by Django 4.1.2 on 2022-10-31 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0024_alter_event_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='account',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='author',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
