# Generated by Django 4.1.2 on 2022-11-01 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_alter_event_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='account',
            field=models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RenameField(
            model_name='event',
            old_name='account',
            new_name='account_id',
        ),
    ]
