# Generated by Django 4.1.2 on 2022-11-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_alter_event_account_rename_account_event_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
