# Generated by Django 4.1.2 on 2022-11-02 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_title_updated_at_alter_title_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewcomment',
            name='event',
            field=models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.event'),
        ),
        migrations.RenameField(
            model_name='reviewcomment',
            old_name='event',
            new_name='event_id',
        ),
    ]
