# Generated by Django 4.1.2 on 2022-11-03 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0032_alter_reviewcomment_event_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='account_id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='author',
        ),
        migrations.AddField(
            model_name='event',
            name='author_id',
            field=models.ForeignKey(db_column='author_id', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
