# Generated by Django 4.1.2 on 2022-11-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_remove_event_account_id_remove_event_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('A', 'Approved'), ('R', 'Rejected'), ('U', 'Under Review'), ('S', 'Submitted'), ('RS', 'Resubmitted'), ('RW', 'Rework')], default='S', max_length=12),
        ),
    ]
