# Generated by Django 4.1.2 on 2022-11-03 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventreviewers',
            name='assigned_reviewer',
            field=models.ForeignKey(db_column='assigned_reviewer_id', on_delete=django.db.models.deletion.CASCADE, related_name='reviewers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RenameField(
            model_name='eventreviewers',
            old_name='assigned_reviewer',
            new_name='assigned_reviewer_id',
        ),
        migrations.AlterField(
            model_name='eventreviewers',
            name='author',
            field=models.ForeignKey(db_column='author_id', on_delete=django.db.models.deletion.CASCADE, related_name='authors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RenameField(
            model_name='eventreviewers',
            old_name='author',
            new_name='author_id',
        ),
        migrations.AlterField(
            model_name='eventreviewers',
            name='event',
            field=models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, related_name='reviewers', to='blog.event'),
        ),
        migrations.RenameField(
            model_name='eventreviewers',
            old_name='event',
            new_name='event_id',
        ),
    ]
