# Generated by Django 4.1.2 on 2022-11-03 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_alter_eventreviewers_assigned_reviewer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventreviewers',
            name='review_status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Completed')], default='P', max_length=10),
        ),
        migrations.AlterField(
            model_name='eventreviewlogs',
            name='status',
            field=models.CharField(choices=[('A', 'Approved'), ('R', 'Rejected'), ('U', 'Under Review'), ('S', 'Submitted'), ('RS', 'Resubmitted'), ('RW', 'Rework')], default='S', max_length=10),
        ),
    ]
