# Generated by Django 4.1.2 on 2022-11-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_alter_eventreviewers_review_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventreviewers',
            name='archived',
            field=models.BooleanField(default=0),
        ),
    ]
